vich_uploader:
    db_driver: orm

    mappings:
        artist_image:
            uri_prefix: /upload/artists
            upload_destination: '%kernel.project_dir%/public/upload/artists'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
